Feature/7/application layout
m-ossolinski/coderscamp_2021_spa_project_2 pull request #17
Opened 2022-01-19 22:09 UTC by Kosik33i6

2022-01-22 06:24 UTC, m-ossolinski requested changes

2022-01-22 06:24 UTC, m-ossolinski commented on src/App.js
> +import { BrowserRouter, Route, Routes } from "react-router-dom";
reorder this import and move it to top

2022-01-22 06:24 UTC, m-ossolinski commented on src/App.js
> +          <Routes>
add separatate folder under `/src` for routes (`/src/routes`) and create routes agregator there

2022-01-22 06:24 UTC, m-ossolinski commented on src/components/layout/MainLayout/MainLayout.js
> +    <div>
redundant div

2022-01-22 06:24 UTC, m-ossolinski commented on src/components/layout/Navigation/Navigation.js
> +export default Navigation;
remove export default

2022-01-22 06:24 UTC, m-ossolinski commented on src/components/layout/MainLayout/MainLayout.js
> +export default MainLayout;
remove export default

2022-01-22 06:24 UTC, m-ossolinski commented on src/components/layout/Header/Header.js
> +export default Header;
remove export default

2022-01-25 15:36 UTC, m-ossolinski approved these changes

2022-01-25 15:36 UTC, m-ossolinski commented on src/App.js
>      <>
reduntant

2022-01-25 16:13 UTC, zakrzaq approved these changes

2022-01-25 16:19 UTC, merged