Feature/39/adding new transaction to db
m-ossolinski/coderscamp_2021_spa_project_2 pull request #50
Opened 2022-02-03 13:54 UTC by axseinga

1. moved baseUrl of transaction db to .env file;
2. add service API to add new transaction
3. fix issues with validation

2022-02-05 09:41 UTC, hannakozak approved these changes

2022-02-06 10:05 UTC, m-ossolinski requested changes

2022-02-06 10:05 UTC, m-ossolinski commented on src/components/common/PageNumberButton/PageNumberButton.js
> +};
are you sure that those files are needed and related to your task?

2022-02-06 10:05 UTC, m-ossolinski commented on src/components/common/PageNumberButton/PageNumberButton.styled.js
> +`;
^

2022-02-06 10:05 UTC, m-ossolinski commented on src/components/common/PaginateButton/PaginateButton.style..js
>  `;
^

2022-02-06 12:33 UTC, closed without merging

2022-02-06 12:33 UTC, axseinga commented
new branch ->  feature/39/adding-new-transaction-to-db-v2